<<<<<<< HEAD
upload_max_filesize  = 1000M
post_max_size        = 1000M
# max_file_uploads   = 25
error_log = /homepages/44/d885318881/htdocs/playfunnel.net/app/public/error_log.txt

=======
upload_max_filesize  = 1000M
post_max_size        = 1000M
# max_file_uploads   = 25
error_log = /homepages/44/d885318881/htdocs/playfunnel.net/app/public/error_log.txt

>>>>>>> 0d6f5c2c18f02c9c7d0a3cb40a1c8218e42ba08f
